name: ReVanced Builder

on: push

jobs:
  build-youtube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "17"

      - name: Patch YouTube APK
        run: java -jar revanced-cli.jar --apk youtube.apk --bundles revanced-patches.jar --merge revanced-integrations.apk --out ${{ github.workspace }}/revanced.apk
        working-directory: ${{ github.workspace }}/sources

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/revanced.apk
